# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VideofusionUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(579, 311)
        self.widget_4 = QtWidgets.QWidget(Form)
        self.widget_4.setGeometry(QtCore.QRect(10, 0, 551, 291))
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.widget_4)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.picpathButton = QtWidgets.QPushButton(self.widget)
        self.picpathButton.setObjectName("picpathButton")
        self.horizontalLayout.addWidget(self.picpathButton)
        self.picpath = QtWidgets.QLineEdit(self.widget)
        self.picpath.setObjectName("picpath")
        self.horizontalLayout.addWidget(self.picpath)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.widget_4)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.outputpathButton = QtWidgets.QPushButton(self.widget_2)
        self.outputpathButton.setObjectName("outputpathButton")
        self.horizontalLayout_2.addWidget(self.outputpathButton)
        self.outputpath = QtWidgets.QLineEdit(self.widget_2)
        self.outputpath.setObjectName("outputpath")
        self.horizontalLayout_2.addWidget(self.outputpath)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.widget_4)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.savenameButton = QtWidgets.QPushButton(self.widget_3)
        self.savenameButton.setObjectName("savenameButton")
        self.horizontalLayout_3.addWidget(self.savenameButton)
        self.savename = QtWidgets.QLineEdit(self.widget_3)
        self.savename.setObjectName("savename")
        self.horizontalLayout_3.addWidget(self.savename)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget_6 = QtWidgets.QWidget(self.widget_4)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.FPSButton = QtWidgets.QPushButton(self.widget_6)
        self.FPSButton.setObjectName("FPSButton")
        self.horizontalLayout_5.addWidget(self.FPSButton)
        self.fps = QtWidgets.QLineEdit(self.widget_6)
        self.fps.setObjectName("fps")
        self.horizontalLayout_5.addWidget(self.fps)
        self.verticalLayout.addWidget(self.widget_6)
        self.widget_5 = QtWidgets.QWidget(self.widget_4)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.progressBar = QtWidgets.QProgressBar(self.widget_5)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_4.addWidget(self.progressBar)
        self.startButton = QtWidgets.QPushButton(self.widget_5)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout_4.addWidget(self.startButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.stopButton = QtWidgets.QPushButton(self.widget_5)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_4.addWidget(self.stopButton)
        self.verticalLayout.addWidget(self.widget_5)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.picpathButton.setText(_translate("Form", "图片路径"))
        self.outputpathButton.setText(_translate("Form", "输出路径"))
        self.savenameButton.setText(_translate("Form", "保存名称"))
        self.FPSButton.setText(_translate("Form", "FPS"))
        self.startButton.setText(_translate("Form", "开始"))
        self.stopButton.setText(_translate("Form", "结束"))
